"""add services hours address to businesses

Revision ID: 373f174f1b59
Revises: a54cd8c083f6
Create Date: 2026-05-24 13:17:15.446321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373f174f1b59'
down_revision: Union[str, Sequence[str], None] = 'a54cd8c083f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('services', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('hours', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'hours')
    op.drop_column('businesses', 'services')
    # ### end Alembic commands ###
