"""add source estimate to jobs, channel to conversations

Revision ID: 51fec6f5e0f3
Revises: 8d31fb7eb164
Create Date: 2026-05-24 15:55:24.738219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51fec6f5e0f3'
down_revision: Union[str, Sequence[str], None] = '8d31fb7eb164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('channel', sa.String(length=10), nullable=False, server_default='sms'))
    op.add_column('jobs', sa.Column('source', sa.String(length=20), nullable=False, server_default='ai'))
    op.add_column('jobs', sa.Column('estimate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'estimate')
    op.drop_column('jobs', 'source')
    op.drop_column('conversations', 'channel')
    # ### end Alembic commands ###
