"""add voice_greeting and system_prompt to businesses

Revision ID: 5608798bd864
Revises: 83e0a98f79d6
Create Date: 2026-05-24 17:42:03.021467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5608798bd864'
down_revision: Union[str, Sequence[str], None] = '83e0a98f79d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('voice_greeting', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'system_prompt')
    op.drop_column('businesses', 'voice_greeting')
    # ### end Alembic commands ###
