"""add reminder_sent to jobs

Revision ID: 8d31fb7eb164
Revises: 373f174f1b59
Create Date: 2026-05-24 13:51:37.014948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d31fb7eb164'
down_revision: Union[str, Sequence[str], None] = '373f174f1b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'reminder_sent')
    # ### end Alembic commands ###
