"""add owner_auth0_id to businesses

Revision ID: f625b2e0b8fc
Revises: 51fec6f5e0f3
Create Date: 2026-05-24 16:31:15.031085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f625b2e0b8fc'
down_revision: Union[str, Sequence[str], None] = '51fec6f5e0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('owner_auth0_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_businesses_owner_auth0_id'), 'businesses', ['owner_auth0_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_owner_auth0_id'), table_name='businesses')
    op.drop_column('businesses', 'owner_auth0_id')
    # ### end Alembic commands ###
