// Joe's Plumbing — demo dataset modeled on the seed.py schema

const business = {
  id: 1,
  name: "Joe's Plumbing",
  twilio_number: "+1 (805) 590-5679",
  services: "Drain cleaning, pipe repair, water heater installation and repair, leak detection, emergency plumbing, bathroom and kitchen plumbing.",
  hours: "Mon–Fri 7:00 AM – 6:00 PM · Sat 8:00 AM – 2:00 PM · Sun closed",
  address: "123 Main Street, Los Angeles, CA 90001",
  rate_per_hour: 145,
};

const technicians = [
  { id: 1, name: "Joe Smith",    phone: "+1 (555) 000-0002", active: true, initials: "JS", color: 250 },
  { id: 2, name: "Mike Johnson", phone: "+1 (555) 000-0003", active: true, initials: "MJ", color: 155 },
  { id: 3, name: "Dave Lee",     phone: "+1 (555) 000-0004", active: true, initials: "DL", color: 75 },
];

const customers = [
  { id: 101, name: "Maria Alvarez",    phone: "+1 (310) 555-0142", created: "Mar 14, 2026", jobs: 3, lifetime: 845 },
  { id: 102, name: "David Park",       phone: "+1 (323) 555-0178", created: "Apr 02, 2026", jobs: 1, lifetime: 320 },
  { id: 103, name: "Linda Cho",        phone: "+1 (818) 555-0193", created: "Apr 19, 2026", jobs: 2, lifetime: 540 },
  { id: 104, name: "Brett Henderson",  phone: "+1 (424) 555-0166", created: "May 05, 2026", jobs: 4, lifetime: 1295 },
  { id: 105, name: "Aisha Mahmood",    phone: "+1 (562) 555-0121", created: "May 11, 2026", jobs: 1, lifetime: 290 },
  { id: 106, name: "Tomás Vega",       phone: "+1 (213) 555-0188", created: "May 18, 2026", jobs: 2, lifetime: 615 },
  { id: 107, name: "Hannah Weiss",     phone: "+1 (310) 555-0119", created: "May 20, 2026", jobs: 1, lifetime: 290 },
  { id: 108, name: "Unknown",          phone: "+1 (818) 555-0177", created: "May 24, 2026", jobs: 0, lifetime: 0 },
  { id: 109, name: "Ravi Patel",       phone: "+1 (310) 555-0104", created: "May 12, 2026", jobs: 2, lifetime: 470 },
  { id: 110, name: "Sarah Donnelly",   phone: "+1 (213) 555-0151", created: "Apr 24, 2026", jobs: 3, lifetime: 920 },
];

const jobs = [
  { id: 5031, customer_id: 104, tech_id: 1, type: "Water heater repair",  status: "in_progress", start: "08:00", end: "10:00", date: "Today",     est: 320, source: "ai" },
  { id: 5032, customer_id: 101, tech_id: 2, type: "Drain cleaning",       status: "completed",   start: "09:00", end: "10:00", date: "Today",     est: 180, source: "ai" },
  { id: 5033, customer_id: 109, tech_id: 3, type: "Leak detection",       status: "confirmed",   start: "10:30", end: "12:00", date: "Today",     est: 220, source: "ai" },
  { id: 5034, customer_id: 103, tech_id: 1, type: "Pipe repair",          status: "confirmed",   start: "11:00", end: "13:00", date: "Today",     est: 410, source: "human" },
  { id: 5035, customer_id: 102, tech_id: 2, type: "Bathroom plumbing",    status: "confirmed",   start: "13:00", end: "15:00", date: "Today",     est: 380, source: "ai" },
  { id: 5036, customer_id: 110, tech_id: 3, type: "Emergency clog",       status: "confirmed",   start: "13:30", end: "15:00", date: "Today",     est: 245, source: "ai" },
  { id: 5037, customer_id: 106, tech_id: 1, type: "Kitchen sink install", status: "confirmed",   start: "15:30", end: "17:00", date: "Today",     est: 290, source: "ai" },
  { id: 5038, customer_id: 105, tech_id: 2, type: "Water heater install", status: "pending",     start: "16:00", end: "18:00", date: "Today",     est: 540, source: "ai" },
  { id: 5039, customer_id: 107, tech_id: 1, type: "Drain cleaning",       status: "confirmed",   start: "09:00", end: "10:30", date: "Tomorrow",  est: 180, source: "ai" },
  { id: 5040, customer_id: 108, tech_id: 3, type: "Leak detection",       status: "pending",     start: "11:00", end: "12:30", date: "Tomorrow",  est: 220, source: "ai" },
  { id: 5029, customer_id: 104, tech_id: 1, type: "Drain cleaning",       status: "no_show",     start: "10:00", end: "11:00", date: "Yesterday", est: 180, source: "ai" },
  { id: 5028, customer_id: 101, tech_id: 2, type: "Pipe repair",          status: "completed",   start: "13:00", end: "15:00", date: "Yesterday", est: 380, source: "ai" },
  { id: 5027, customer_id: 110, tech_id: 3, type: "Water heater repair",  status: "completed",   start: "08:00", end: "10:00", date: "Yesterday", est: 320, source: "ai" },
  { id: 5026, customer_id: 102, tech_id: 1, type: "Bathroom plumbing",    status: "cancelled",   start: "11:00", end: "13:00", date: "Yesterday", est: 380, source: "ai" },
];

const conversations = [
  {
    id: 901,
    customer_id: 108,
    channel: "voice",
    started_at: "Today · 11:42 AM",
    last_at: "11:46 AM",
    unread: true,
    booked: false,
    duration: "3m 24s",
    preview: "Caller asked about emergency leak under kitchen sink. Hung up before booking.",
    messages: [
      { dir: "in",  body: "Hi, my kitchen sink is leaking everywhere and there's water all over the floor.", time: "11:42 AM" },
      { dir: "out", body: "I'm sorry to hear that. I can get someone out today. Can I get your name and the address?", time: "11:42 AM" },
      { dir: "in",  body: "Yeah it's bad. Address is 4421 Atwater Ave.", time: "11:43 AM" },
      { dir: "out", body: "Got it. Let me check who's available.", time: "11:43 AM" },
      { tool: "check_availability", args: "", result: "3 slots returned", time: "11:43 AM" },
      { dir: "out", body: "I can get Dave out at 2:30 PM today, or Joe at 4 PM. Which works better?", time: "11:43 AM" },
      { dir: "in",  body: "Let me call my husband and call back.", time: "11:44 AM" },
      { dir: "out", body: "Of course. Call back any time at this number and I'll have your info ready.", time: "11:44 AM" },
    ],
  },
  {
    id: 902,
    customer_id: 105,
    channel: "sms",
    started_at: "Today · 10:18 AM",
    last_at: "10:21 AM",
    unread: false,
    booked: true,
    preview: "Booked water heater install for 4 PM today.",
    messages: [
      { dir: "in",  body: "Hey, my water heater is making a weird humming noise. Can someone take a look today?", time: "10:18 AM" },
      { dir: "out", body: "Hi! That usually means sediment buildup, sometimes a failing element. I can send a tech out today. What's your address?", time: "10:18 AM" },
      { dir: "in",  body: "812 La Brea Ave Apt 4", time: "10:19 AM" },
      { tool: "check_availability", args: "", result: "5 slots returned", time: "10:19 AM" },
      { dir: "out", body: "I have 1 PM with Mike or 4 PM with Mike. Either work?", time: "10:19 AM" },
      { dir: "in",  body: "4pm works", time: "10:20 AM" },
      { tool: "book_job", args: "slot_id=44, job_type=Water heater install", result: "Booked", time: "10:20 AM" },
      { dir: "out", body: "Booked! Mike will be there today at 4:00 PM. Estimate is $540. Reply STOP to opt out.", time: "10:20 AM" },
      { dir: "in",  body: "Great thanks", time: "10:21 AM" },
    ],
  },
  {
    id: 903,
    customer_id: 110,
    channel: "voice",
    started_at: "Today · 09:04 AM",
    last_at: "09:09 AM",
    unread: false,
    booked: true,
    duration: "4m 51s",
    preview: "Emergency clog booked for 1:30 PM with Dave.",
    messages: [
      { dir: "in",  body: "Hi this is Sarah Donnelly, my toilet is overflowing.", time: "09:04 AM" },
      { dir: "out", body: "Sarah, I'm sorry. Let's get you on the schedule. Same address as last time on Echo Park?", time: "09:04 AM" },
      { dir: "in",  body: "Yes same address.", time: "09:05 AM" },
      { tool: "check_availability", args: "", result: "3 slots returned", time: "09:05 AM" },
      { dir: "out", body: "Dave can be there at 1:30 PM today. Does that work?", time: "09:05 AM" },
      { dir: "in",  body: "Yes please.", time: "09:06 AM" },
      { tool: "book_job", args: "slot_id=38, job_type=Emergency clog", result: "Booked", time: "09:06 AM" },
      { dir: "out", body: "All set. Dave Lee will be there today at 1:30 PM. You'll get a text reminder an hour before.", time: "09:06 AM" },
    ],
  },
  {
    id: 904,
    customer_id: 107,
    channel: "sms",
    started_at: "Yesterday · 06:32 PM",
    last_at: "Yesterday · 06:38 PM",
    unread: false,
    booked: true,
    preview: "Booked drain cleaning for tomorrow 9 AM.",
    messages: [
      { dir: "in",  body: "Bathroom sink draining super slow", time: "Yest 06:32 PM" },
      { dir: "out", body: "Hi! Sounds like buildup in the trap or pipe. I can schedule a drain cleaning. Any preference on time?", time: "Yest 06:32 PM" },
      { dir: "in",  body: "Tomorrow morning if possible", time: "Yest 06:33 PM" },
      { tool: "check_availability", args: "", result: "4 slots returned", time: "Yest 06:33 PM" },
      { dir: "out", body: "Joe can come tomorrow at 9 AM. Want me to book it?", time: "Yest 06:33 PM" },
      { dir: "in",  body: "yes pls", time: "Yest 06:38 PM" },
      { tool: "book_job", args: "slot_id=29, job_type=Drain cleaning", result: "Booked", time: "Yest 06:38 PM" },
      { dir: "out", body: "Booked! Joe will be there tomorrow at 9:00 AM. Estimate $180. Reply STOP to opt out.", time: "Yest 06:38 PM" },
    ],
  },
  {
    id: 905,
    customer_id: 102,
    channel: "sms",
    started_at: "Yesterday · 02:11 PM",
    last_at: "Yesterday · 02:14 PM",
    unread: false,
    booked: false,
    preview: "Asked about water heater pricing — no booking.",
    messages: [
      { dir: "in",  body: "How much for a water heater replacement, 40 gallon?", time: "Yest 02:11 PM" },
      { dir: "out", body: "For a standard 40-gallon tank install, we typically quote $540 plus the cost of the unit. We'd send a tech for a quick on-site quote first. Want to schedule that?", time: "Yest 02:11 PM" },
      { dir: "in",  body: "Just shopping around, thanks", time: "Yest 02:14 PM" },
      { dir: "out", body: "Sounds good. Call or text any time if you decide to go ahead.", time: "Yest 02:14 PM" },
    ],
  },
  {
    id: 906,
    customer_id: 103,
    channel: "sms",
    started_at: "Yesterday · 11:02 AM",
    last_at: "Yesterday · 11:09 AM",
    unread: false,
    booked: true,
    preview: "Pipe repair booked for today 11 AM (rescheduled from Sat).",
    messages: [
      { dir: "in",  body: "I need to move my Saturday appointment", time: "Yest 11:02 AM" },
      { dir: "out", body: "Of course. Which appointment, and when would you like to move it to?", time: "Yest 11:02 AM" },
      { dir: "in",  body: "The pipe repair, can we do Monday morning?", time: "Yest 11:03 AM" },
      { tool: "check_availability", args: "", result: "4 slots returned", time: "Yest 11:03 AM" },
      { dir: "out", body: "I have Joe at 11 AM Monday. Want me to move it there?", time: "Yest 11:03 AM" },
      { dir: "in",  body: "yes thanks", time: "Yest 11:09 AM" },
      { tool: "reschedule_job", args: "job_id=5034, new_slot_id=51", result: "Rescheduled", time: "Yest 11:09 AM" },
      { dir: "out", body: "Rescheduled! Joe will be there Monday at 11 AM.", time: "Yest 11:09 AM" },
    ],
  },
  {
    id: 907,
    customer_id: 106,
    channel: "voice",
    started_at: "Yesterday · 09:21 AM",
    last_at: "09:25 AM",
    unread: false,
    booked: true,
    duration: "3m 47s",
    preview: "Kitchen sink install — booked Joe at 3:30 PM today.",
    messages: [
      { dir: "in",  body: "I just got a new sink and I need it installed.", time: "Yest 09:21 AM" },
      { dir: "out", body: "Great, we can do that. Did you get a new faucet too, or just the sink?", time: "Yest 09:21 AM" },
      { dir: "in",  body: "New sink and new faucet.", time: "Yest 09:22 AM" },
      { tool: "check_availability", args: "", result: "3 slots returned", time: "Yest 09:22 AM" },
      { dir: "out", body: "I have Joe at 3:30 PM Monday. Want me to book that?", time: "Yest 09:22 AM" },
      { dir: "in",  body: "Yeah that's good.", time: "Yest 09:23 AM" },
      { tool: "book_job", args: "slot_id=49, job_type=Kitchen sink install", result: "Booked", time: "Yest 09:23 AM" },
      { dir: "out", body: "Booked. Joe will be there Monday at 3:30 PM. Estimate is $290.", time: "Yest 09:23 AM" },
    ],
  },
];

const feed = [
  { id: 1, kind: "booked",     who: "Maria Alvarez",  verb: "booked drain cleaning",       when: "2m ago",  meta: "via voice · Mike J · $180",       time: "11:46" },
  { id: 2, kind: "info",       who: "Unknown",        verb: "asked about emergency leak",  when: "8m ago",  meta: "via voice · 3m 24s · no booking", time: "11:42" },
  { id: 3, kind: "booked",     who: "Aisha Mahmood",  verb: "booked water heater install", when: "32m ago", meta: "via SMS · Mike J · $540",         time: "10:21" },
  { id: 4, kind: "booked",     who: "Sarah Donnelly", verb: "booked emergency clog",       when: "1h ago",  meta: "via voice · Dave L · $245",       time: "09:09" },
  { id: 5, kind: "reschedule", who: "Linda Cho",      verb: "rescheduled to Monday 11 AM", when: "Yest",    meta: "via SMS · Joe S",                 time: "11:09" },
  { id: 6, kind: "booked",     who: "Tomás Vega",     verb: "booked kitchen sink install", when: "Yest",    meta: "via voice · Joe S · $290",        time: "09:25" },
  { id: 7, kind: "cancelled",  who: "David Park",     verb: "cancelled bathroom plumbing", when: "Yest",    meta: "via SMS · refunded $0",           time: "07:02" },
  { id: 8, kind: "booked",     who: "Hannah Weiss",   verb: "booked drain cleaning",       when: "Yest",    meta: "via SMS · Joe S · $180",          time: "18:38" },
];

const kpis = {
  ai_booked_today: 6,
  ai_booked_revenue: 1855,
  human_booked_today: 1,
  calls_handled: 11,
  calls_answered_pct: 100,
  avg_response_sec: 4.2,
  customers_total: customers.length,
};

export const AIRDATA = { business, technicians, customers, jobs, conversations, feed, kpis };
